# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'primer.ui'
#
# Created: Thu Aug 28 15:55:30 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(739, 932)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MV Boli"))
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 719, 821))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setMinimumSize(QtCore.QSize(650, 800))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 621, 511))
        self.groupBox_3.setMinimumSize(QtCore.QSize(200, 300))
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 30, 601, 241))
        self.plainTextEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.layoutWidget_3 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 270, 601, 60))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_6.setContentsMargins(10, 5, 5, 5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_11 = QtGui.QLabel(self.layoutWidget_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_6.addWidget(self.label_11, 0, 0, 1, 1)
        self.commandLinkButton = QtGui.QCommandLinkButton(self.layoutWidget_3)
        self.commandLinkButton.setMaximumSize(QtCore.QSize(160, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Filesystem-folder-grey-open-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton.setIcon(icon)
        self.commandLinkButton.setIconSize(QtCore.QSize(30, 30))
        self.commandLinkButton.setObjectName(_fromUtf8("commandLinkButton"))
        self.gridLayout_6.addWidget(self.commandLinkButton, 0, 1, 1, 1)
        self.line_4 = QtGui.QFrame(self.layoutWidget_3)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_6.addWidget(self.line_4, 1, 0, 1, 1)
        self.line_5 = QtGui.QFrame(self.layoutWidget_3)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_6.addWidget(self.line_5, 1, 1, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 340, 601, 161))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.layoutWidget_5 = QtGui.QWidget(self.groupBox_6)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 30, 581, 121))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget_5)
        self.gridLayout_7.setContentsMargins(10, 5, 5, 5)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.comboBox = QtGui.QComboBox(self.layoutWidget_5)
        self.comboBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBox, 3, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_7.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_7.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.layoutWidget_5)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_7.addWidget(self.label_23, 2, 2, 1, 2)
        self.pushButton_3 = QtGui.QPushButton(self.layoutWidget_5)
        self.pushButton_3.setMinimumSize(QtCore.QSize(180, 50))
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_7.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.pushButton = QtGui.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(260, 550, 120, 50))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 20, 461, 561))
        self.groupBox_5.setMinimumSize(QtCore.QSize(200, 300))
        self.groupBox_5.setAutoFillBackground(False)
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.plainTextEdit_5 = QtGui.QPlainTextEdit(self.groupBox_5)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(10, 30, 371, 261))
        self.plainTextEdit_5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.plainTextEdit_5.setObjectName(_fromUtf8("plainTextEdit_5"))
        self.layoutWidget_6 = QtGui.QWidget(self.groupBox_5)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 290, 371, 60))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget_6)
        self.gridLayout_8.setContentsMargins(10, 5, 5, 5)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.commandLinkButton_5 = QtGui.QCommandLinkButton(self.layoutWidget_6)
        self.commandLinkButton_5.setMaximumSize(QtCore.QSize(160, 16777215))
        self.commandLinkButton_5.setIcon(icon)
        self.commandLinkButton_5.setIconSize(QtCore.QSize(30, 30))
        self.commandLinkButton_5.setObjectName(_fromUtf8("commandLinkButton_5"))
        self.gridLayout_8.addWidget(self.commandLinkButton_5, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget_6)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.layoutWidget_6)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_8.addWidget(self.line, 1, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.layoutWidget_6)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_8.addWidget(self.line_2, 1, 1, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 360, 301, 191))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_10.setContentsMargins(10, 5, 5, 5)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox_8)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.gridLayout_10.addWidget(self.radioButton_4, 5, 0, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.groupBox_8)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout_10.addWidget(self.radioButton, 3, 0, 1, 1)
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox_8)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.gridLayout_10.addWidget(self.radioButton_3, 4, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_8)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_10.addWidget(self.label_12, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_10.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_10.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_8)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_10.addWidget(self.label, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem, 2, 0, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_6.setGeometry(QtCore.QRect(330, 430, 120, 50))
        self.pushButton_6.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 20, 631, 661))
        self.groupBox_4.setMinimumSize(QtCore.QSize(200, 300))
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.groupBox_4)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(10, 30, 601, 241))
        self.plainTextEdit_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.layoutWidget_4 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 270, 601, 61))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.gridLayout_9 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_9.setContentsMargins(10, 5, 5, 5)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_14 = QtGui.QLabel(self.layoutWidget_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_9.addWidget(self.label_14, 0, 0, 1, 1)
        self.commandLinkButton_2 = QtGui.QCommandLinkButton(self.layoutWidget_4)
        self.commandLinkButton_2.setMaximumSize(QtCore.QSize(160, 16777215))
        self.commandLinkButton_2.setIcon(icon)
        self.commandLinkButton_2.setIconSize(QtCore.QSize(30, 30))
        self.commandLinkButton_2.setObjectName(_fromUtf8("commandLinkButton_2"))
        self.gridLayout_9.addWidget(self.commandLinkButton_2, 0, 1, 1, 1)
        self.line_6 = QtGui.QFrame(self.layoutWidget_4)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_9.addWidget(self.line_6, 1, 0, 1, 1)
        self.line_7 = QtGui.QFrame(self.layoutWidget_4)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_9.addWidget(self.line_7, 1, 1, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(self.groupBox_4)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 350, 601, 301))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.groupBox = QtGui.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 591, 231))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget_7 = QtGui.QWidget(self.groupBox)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 30, 571, 188))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.gridLayout_11 = QtGui.QGridLayout(self.layoutWidget_7)
        self.gridLayout_11.setContentsMargins(10, 5, 5, 5)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_24 = QtGui.QLabel(self.layoutWidget_7)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_11.addWidget(self.label_24, 5, 0, 1, 1)
        self.lineEdit_20 = QtGui.QLineEdit(self.layoutWidget_7)
        self.lineEdit_20.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_20.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.gridLayout_11.addWidget(self.lineEdit_20, 5, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget_7)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_11.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget_7)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_11.addWidget(self.label_16, 4, 0, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.layoutWidget_7)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_11.addWidget(self.lineEdit_4, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget_7)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_11.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget_7)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_11.addWidget(self.label_5, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem1, 1, 1, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.layoutWidget_7)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_11.addWidget(self.lineEdit_5, 2, 2, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.layoutWidget_7)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout_11.addWidget(self.lineEdit_7, 4, 2, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.layoutWidget_7)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout_11.addWidget(self.lineEdit_6, 3, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget_7)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_11.addWidget(self.label_13, 6, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.layoutWidget_7)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_11.addWidget(self.checkBox, 6, 2, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.page)
        self.pushButton_7.setGeometry(QtCore.QRect(540, 10, 21, 23))
        self.pushButton_7.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/to_copy/images/left20.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setIconSize(QtCore.QSize(10, 10))
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(self.page)
        self.pushButton_8.setGeometry(QtCore.QRect(560, 10, 21, 23))
        self.pushButton_8.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/to_copy/images/right20.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon2)
        self.pushButton_8.setIconSize(QtCore.QSize(10, 10))
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.page_2)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 10, 591, 291))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(560, 0, 21, 23))
        self.pushButton_4.setText(_fromUtf8(""))
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setIconSize(QtCore.QSize(10, 10))
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(540, 0, 21, 23))
        self.pushButton_5.setText(_fromUtf8(""))
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setIconSize(QtCore.QSize(10, 10))
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.layoutWidget_8 = QtGui.QWidget(self.page_2)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 40, 571, 251))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.gridLayout_12 = QtGui.QGridLayout(self.layoutWidget_8)
        self.gridLayout_12.setContentsMargins(10, 5, 5, 5)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.lineEdit_12 = QtGui.QLineEdit(self.layoutWidget_8)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout_12.addWidget(self.lineEdit_12, 1, 3, 1, 1)
        self.lineEdit_18 = QtGui.QLineEdit(self.layoutWidget_8)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.gridLayout_12.addWidget(self.lineEdit_18, 6, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem2, 4, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.layoutWidget_8)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_12.addWidget(self.label_22, 0, 3, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.layoutWidget_8)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout_12.addWidget(self.lineEdit_13, 2, 1, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.layoutWidget_8)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout_12.addWidget(self.lineEdit_14, 2, 3, 1, 1)
        self.lineEdit_15 = QtGui.QLineEdit(self.layoutWidget_8)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.gridLayout_12.addWidget(self.lineEdit_15, 3, 1, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(self.layoutWidget_8)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridLayout_12.addWidget(self.lineEdit_16, 3, 3, 1, 1)
        self.lineEdit_17 = QtGui.QLineEdit(self.layoutWidget_8)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.gridLayout_12.addWidget(self.lineEdit_17, 5, 1, 1, 1)
        self.lineEdit_19 = QtGui.QLineEdit(self.layoutWidget_8)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.gridLayout_12.addWidget(self.lineEdit_19, 7, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.layoutWidget_8)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_12.addWidget(self.label_21, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget_8)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_12.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget_8)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_12.addWidget(self.label_17, 1, 0, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.layoutWidget_8)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_12.addWidget(self.lineEdit_8, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget_8)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_12.addWidget(self.label_8, 6, 0, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.layoutWidget_8)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_12.addWidget(self.lineEdit_9, 2, 2, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.layoutWidget_8)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout_12.addWidget(self.lineEdit_11, 3, 2, 1, 1)
        self.label_19 = QtGui.QLabel(self.layoutWidget_8)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_12.addWidget(self.label_19, 7, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget_8)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_12.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget_8)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_12.addWidget(self.label_18, 5, 0, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.layoutWidget_8)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout_12.addWidget(self.lineEdit_10, 1, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget_8)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_12.addWidget(self.label_20, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.pushButton_2 = QtGui.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 700, 120, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 739, 24))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.menubar.setFont(font)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuSequences = QtGui.QMenu(self.menubar)
        self.menuSequences.setObjectName(_fromUtf8("menuSequences"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionClear_all = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.actionClear_all.setFont(font)
        self.actionClear_all.setObjectName(_fromUtf8("actionClear_all"))
        self.actionAbout = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionDocumentation = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.actionDocumentation.setFont(font)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.actionConvert_Fasta_Excel = QtGui.QAction(MainWindow)
        self.actionConvert_Fasta_Excel.setObjectName(_fromUtf8("actionConvert_Fasta_Excel"))
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuAbout.addAction(self.actionAbout)
        self.menuSequences.addAction(self.actionClear_all)
        self.menuSequences.addSeparator()
        self.menubar.addAction(self.menuSequences.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Primer Factory ", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#55aaff;\">Primer Factory Qt</span></p></body></html>", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Paste Query Sequence in Plain Text or Fasta format", None))
        self.label_11.setText(_translate("MainWindow", "No file selected.", None))
        self.commandLinkButton.setText(_translate("MainWindow", "Or choose file", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Settings", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "0", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "1", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "2", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "3", None))
        self.label_9.setText(_translate("MainWindow", "Choose primer file", None))
        self.label_10.setText(_translate("MainWindow", "Allowed missmatches", None))
        self.label_23.setText(_translate("MainWindow", "No file selected.", None))
        self.pushButton_3.setText(_translate("MainWindow", "Open Primer File", None))
        self.pushButton.setText(_translate("MainWindow", "Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Primer Search", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Paste Query Sequence in Plain Text or Fasta format", None))
        self.commandLinkButton_5.setText(_translate("MainWindow", "Or choose file", None))
        self.label_3.setText(_translate("MainWindow", "No file selected.", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Settings", None))
        self.radioButton_4.setText(_translate("MainWindow", "Salt adjusted", None))
        self.radioButton.setText(_translate("MainWindow", "Nearest Neighbour", None))
        self.radioButton_3.setText(_translate("MainWindow", "Basic", None))
        self.label_12.setText(_translate("MainWindow", "Salt Concentration (mM)", None))
        self.lineEdit.setText(_translate("MainWindow", "50", None))
        self.lineEdit_3.setText(_translate("MainWindow", "50", None))
        self.label.setText(_translate("MainWindow", "Primer Concentration (nM)", None))
        self.pushButton_6.setText(_translate("MainWindow", "Calculate", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Anealing Temp. Calculator", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Paste Query Sequence in Plain Text or Fasta format", None))
        self.label_14.setText(_translate("MainWindow", "No file selected.", None))
        self.commandLinkButton_2.setText(_translate("MainWindow", "Or choose file", None))
        self.groupBox.setTitle(_translate("MainWindow", "Main settings", None))
        self.label_24.setText(_translate("MainWindow", "Number of primers to return", None))
        self.lineEdit_20.setText(_translate("MainWindow", "1", None))
        self.label_15.setText(_translate("MainWindow", "Excluded regions", None))
        self.label_16.setText(_translate("MainWindow", "Product size range", None))
        self.label_2.setText(_translate("MainWindow", "Included regions", None))
        self.label_5.setText(_translate("MainWindow", "Targets", None))
        self.lineEdit_7.setText(_translate("MainWindow", "401-500 301-400", None))
        self.label_13.setText(_translate("MainWindow", "Open raw Primer3 files after run", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Advanced settings", None))
        self.lineEdit_12.setText(_translate("MainWindow", "27", None))
        self.lineEdit_18.setText(_translate("MainWindow", "50", None))
        self.label_22.setText(_translate("MainWindow", "Maximum", None))
        self.lineEdit_13.setText(_translate("MainWindow", "53", None))
        self.lineEdit_14.setText(_translate("MainWindow", "58", None))
        self.lineEdit_15.setText(_translate("MainWindow", "20.0", None))
        self.lineEdit_16.setText(_translate("MainWindow", "80.0", None))
        self.lineEdit_17.setText(_translate("MainWindow", "100", None))
        self.lineEdit_19.setText(_translate("MainWindow", "50", None))
        self.label_21.setText(_translate("MainWindow", "Optimum", None))
        self.label_7.setText(_translate("MainWindow", "Primer GC%", None))
        self.label_17.setText(_translate("MainWindow", "Primer Size", None))
        self.lineEdit_8.setText(_translate("MainWindow", "20", None))
        self.label_8.setText(_translate("MainWindow", "Monovalent cations (mM)", None))
        self.lineEdit_9.setText(_translate("MainWindow", "55", None))
        self.lineEdit_11.setText(_translate("MainWindow", "50.0", None))
        self.label_19.setText(_translate("MainWindow", "Oligo DNA conc. (mM)", None))
        self.label_6.setText(_translate("MainWindow", "Primer Tm", None))
        self.label_18.setText(_translate("MainWindow", "Max. Tm Difference", None))
        self.lineEdit_10.setText(_translate("MainWindow", "18", None))
        self.label_20.setText(_translate("MainWindow", "Minimum", None))
        self.pushButton_2.setText(_translate("MainWindow", "Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Primer Design", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.menuSequences.setTitle(_translate("MainWindow", "Options", None))
        self.actionClear_all.setText(_translate("MainWindow", "Clear all fields", None))
        self.actionAbout.setText(_translate("MainWindow", "About PrimerFactoryQt", None))
        self.actionAbout.setToolTip(_translate("MainWindow", "About", None))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation", None))
        self.actionDocumentation.setToolTip(_translate("MainWindow", "Help", None))
        self.actionConvert_Fasta_Excel.setText(_translate("MainWindow", "Convert  Fasta <-> CSV", None))

import primer_rc
